### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by eklein**
Let me know if the yahoo app developer consumer key, secret, and application ID are necessary. If they are, I can document how I got those setup as well.

### CODE REVIEW

**Comment by ghost** [comment]
I second that. I removed it from my config file.

**Comment by ghost** [comment]
additionally Grab the minified v3 version of d3js from https://d3js.org/d3.v3.min.js and place it into:

[your-web-root]/nestgraph/d3.min.js

this link is just text? can we get the actual zip download link or at least a link with what is to be done with the text. do we just put it in a regular file and name it d3.min.js? 

It doesn't appear the init_devices.php is working as when I go to nestgraph/index.php I only see a tab that says "not set" with no selectable devices.

When running test.php I don't see the text "fly by" as I did with the original nestgraph. It appears to hang and then returns:
[root@localhost nestgraph]# php test.php
Name             : Not Set
Heating             : 0
Cooling             : 0
Timestamp           : 2016-08-22 17:35:07
Target temperature  : 75.10
Current temperature : 75.45
Current humidity    : 45

Which to me indicates that I am able to login to my nest, but it is not retrieving the info it needs? Is there a step being missed in editing the init_devices.php?

MariaDB [nest]> SELECT \* FROM devices;
+----+------------------+---------+
| id | serial           | name    |
+----+------------------+---------+
|  1 | 09xxxxxxxxxxxxxxGF | Not Set |
+----+------------------+---------+
1 row in set (0.00 sec)

I can see my nest id, serial, and name is blank(I'm sure that's not a problem) So it would seem that init_devices.php registered my device. The other tables are empty, so it's not getting data from the nest (or at least not placing it in the tables)

I am stumped.

I am not receiving any PHP errors.

**Comment by mycon** [comment]
The init_devices should just be pulling the label from nest's database (on the website at gear->thermostats->where->label).
The "Not Set" seems like it got the data from nest, but you've never labeled it.  Failing to login should have thrown an error.

Unfortunately, Yahoo closed up their easy, public api access and the insert.php expects/needs the various tokens/app ids to pull the current outdoor temp, pressure, humidity.  If you don't want this you can comment out those lines in insert.php (but outdoor temp is the biggest driver in energy, and one of the big things plotted/tracked on the web ui).

"Current humidity" is the last line printed, so you've probably got everything working fine there.

**Comment by ghost** [comment]
So I ran the php scripts from cmd line and was able to populate the tables. I labeled my nest and it returned the change propagates the device table. So I know that mysql is accepting the input from cmd line. APIs are working. If I run the the remaining php scripts from cmd line it will populate the DB. Still I am left with a blank page with not set. 

php error returns Undefined variable: options from index.php

I commented out <?php echo $options;?> as it was not allowing $options to be called after the variable was assigned and closed above with ?>

Additionally I didn't understand the steps for using the d3.min.js. I commented that out and sited the url instead. So I have graphs now, but they are empty. I'm still not able to insert into my DB.

**Comment by mycon** [comment]
Dono.. look like it hit the exception so options wasn't ever set.  Maybe
print out the errors and see what went wrong.

**Comment by ghost** [comment]
No errors. I let it sit over night came home refreshed my browser and all the data was there. It must have needed to wait for a data pull or one of the cronjobs to execute. Either way it looks great and can't wait to start. Me and a friend are building auto vents that already use the nest api.

**Pull request merged**
